# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Noah James
email: nobobjam@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal and professional website for Noah James.
  This website gives additional information about Noah James, including
  contact information. The blog posts on this website are showcases of
  Noah James' personal and professional work as a software developer, 
  musician, and endurance athlete.
github: [metadata]
repository: "noajam/noajam.github.io"
github_username: noajam
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Noah James"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Soon-to-be graduate of CU Boulder with a Masters in Computer Science. Interested in artificial intelligence, computer graphics, and modeling and simulation.\n\nCurrently looking for work!"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/noah-r-james/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/noajam/"
    - label: "Email"
      icon: "fab fa-fw fa-envelope"
      url: "mailto:nobobjam@gmail.com"
    

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/noajam"
    - label: "Email"
      icon: "fab fa-fw fa-email"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
